//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class film_seans
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> seans { get; set; }
        public Nullable<int> hall { get; set; }
        public Nullable<int> row { get; set; }
        public Nullable<int> seat { get; set; }
    }
}
